game/config/routes.rb
Rails.application.routes.draw do
  #routes
   resources :throwings
   root "throwings#index"
end

game/app/models/throwing.rb
class Throwing < ActiveRecord::Base
    def calculate_score()
      turn = 0
      frames = []

      entrada.upcase.split('').each do |char|
        # Toma un turno y si no existe crea uno nuevo
        frame = frames[turn] || { rolls: [] }
        frames[turn] = frame

        last_frame = frames.length == 10

        case char
        when 'X' # Strike
          frame[:rolls] << 10
          frame[:strike] = true
          turn += 1 unless last_frame
        when '/' # Spare
          frame[:rolls] << 10 - frame[:rolls].first
          frame[:spare] = true
          turn += 1 unless last_frame
        when '-' # Miss
          frame[:rolls] << 0

          # pasar al siguiente luego de dos tiros
          if !last_frame && frame[:rolls].length == 2
            turn += 1
          end
        else # number
          frame[:rolls] << char.to_i

          # pasar al siguente frame luego de dos tiros
          if !last_frame && frame[:rolls].length == 2
            turn += 1
          end
        end
      end

      # analizar turnos
      score = 0

      frames.each_with_index do |frame, index|
        if frame[:strike]
          next_frame = frames[index + 1]

          if next_frame
            if next_frame[:rolls].length >= 2
              score += next_frame[:rolls][0...2].sum
            else
              score += next_frame[:rolls].first

              next_next_frame = frames[index + 2]
              score += next_next_frame[:rolls].first if next_next_frame
            end
          end
          
        end

        if frame[:spare]
          next_frame = frames[index + 1]

          if next_frame
            score += next_frame[:rolls].first
          end
        end

        # siempre sumar los tiros del frame
        score += frame[:rolls].sum

      end
      self.score = score

    end
end

game/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

game/app/controllers/throwings_controller.rb
class ThrowingsController < ApplicationController
    def index
      @throwings = Throwing.all()
    end

    def new
      @throwing = Throwing.new
    end

    def create
      @throwing = Throwing.new(throwing_params)
      @throwing.calculate_score()

      # Verificaremos si la entrada se guardo
      if @throwing.save
        redirect_to @throwing
      else
	render 'new'
      end
    end

    def show
       @throwing = Throwing.find(params[:id])
    end

    private

    def throwing_params
      params.require(:throwing).permit(:entrada)
    end
end

game/app/helpers/application_helper.rb
module ApplicationHelper
end

game/app/helpers/throwings_helper.rb
module ThrowingsHelper
end

game/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

game/app/views/throwings/index.html.erb
<div class="container">
      <h1 class="title init">Bowling Game<h1>
	 <div class="newScore">
                <%= link_to "Add new game", new_throwing_path, class: "index-link" %>
	  </div>

      <div class="index">

      <ul>
	    <li class="subTitle">Input</li>
            <% @throwings.each do |throwing| %>
              <li> <%= throwing.entrada %> </li>  
            <% end %>
      </ul>

      <ul>
	    <li class="subTitle">Score</li>
            <% @throwings.each do |throwing| %>
              <li> <%= throwing.score %> </li>  
            <% end %>
      </ul>
      </div>

</div>

game/app/views/throwings/new.html.erb
<div class="container">
	<h1 class="title init">Bowling Game<h1>
			<div class="newScore">
				<%= link_to "Add new game", new_throwing_path, class: "index-link" %>
			</div>


        <div class="cal">
          <p class="text">Calculate your final result of your game line!</p>

                <%-#verificar si el usuario ingresa 20 o 21 numeros si no enviar un aviso que le falta ingresar valores.-%>

		<%= form_for @throwing do |throwing_form| %>
			<%= throwing_form.text_field :entrada %>
			<%= throwing_form.submit "Score", id:'button' %>
		<% end %>
	
	</div>

</div>

game/app/views/throwings/show.html.erb
<h1 class="title init">Score Total<h1>
		<div class="newScore">
			<%= link_to "All results", throwings_path, class: "index-link" %>
		</div>

<p class="text"><%= @throwing.score %></p>